#!/usr/bin/env sh
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.tsx?$' | sed 's| |\\ |g')

if [ -z "$STAGED_FILES" ]; then
  echo "No staged TypeScript files to check."
else
  echo "Type checking..."
  tsc -b
  echo "Running eslint and prettier on staged files..."
  eslint $STAGED_FILES --fix
  prettier $STAGED_FILES --write --ignore-unknown
  git update-index --again
fi
